@echo off
echo [PyQuest] Starting project maintenance...
echo [1/3] Cleaning project...
call flutter clean
echo [2/3] Fetching dependencies...
call flutter pub get
echo [3/3] Re-linking native dependencies...
call flutter pub get
echo.
echo [PyQuest] Maintenance complete. You can now run 'flutter run'.
pause
