// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxalXRHVVHiXhCqkm0KjuIO4NjbcDR4eI',
    appId: '1:3034074101:web:7ab015679bcb36198c2ebc',
    messagingSenderId: '3034074101',
    projectId: 'pyquest-976f3',
    authDomain: 'pyquest-976f3.firebaseapp.com',
    storageBucket: 'pyquest-976f3.firebasestorage.app',
    measurementId: 'G-KKLW8VTC8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwDqUFvjJyolBwSD6L5sMP5vXoXii7mLo',
    appId: '1:3034074101:android:5a963750dc36ed7b8c2ebc',
    messagingSenderId: '3034074101',
    projectId: 'pyquest-976f3',
    storageBucket: 'pyquest-976f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf5B07jpG_v1bdLZYkw2AVHFjPgK0vupQ',
    appId: '1:3034074101:ios:14a47ae2a03553b38c2ebc',
    messagingSenderId: '3034074101',
    projectId: 'pyquest-976f3',
    storageBucket: 'pyquest-976f3.firebasestorage.app',
    iosBundleId: 'com.example.projectPart1V1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf5B07jpG_v1bdLZYkw2AVHFjPgK0vupQ',
    appId: '1:3034074101:ios:14a47ae2a03553b38c2ebc',
    messagingSenderId: '3034074101',
    projectId: 'pyquest-976f3',
    storageBucket: 'pyquest-976f3.firebasestorage.app',
    iosBundleId: 'com.example.projectPart1V1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxalXRHVVHiXhCqkm0KjuIO4NjbcDR4eI',
    appId: '1:3034074101:web:b06a4174a33fbfd48c2ebc',
    messagingSenderId: '3034074101',
    projectId: 'pyquest-976f3',
    authDomain: 'pyquest-976f3.firebaseapp.com',
    storageBucket: 'pyquest-976f3.firebasestorage.app',
    measurementId: 'G-21YWXZQLLY',
  );
}
